apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-user
  name: backend-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - image: ahmedhesham6/udagram-api-user:v1.0.0
        name: backend-user
        imagePullPolicy: Always     
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "4Gi"
            cpu: "500m"              
        env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: udagram-env-configmap 
              key: url
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: udagram-env-configmap 
              key: bucket_arn
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: udagram-env-configmap 
              key: aws_profile
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: udagram-env-configmap 
              key: bucket_region
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: udagram-env-configmap 
              key: database_name
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: udagram-env-configmap 
              key: database_host
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: udagram-env-secret
              key: jwt_secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: udagram-env-secret
              key: database_password
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: udagram-env-secret
              key: database_username          
      restartPolicy: Always