apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        api: external        
    spec:
      containers:
      - image: ahmedhesham6/udagram-frontend:v1.0.0
        name: frontend
        imagePullPolicy: Always  
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"     
        ports:
        - containerPort: 80        
      restartPolicy: Always
